package com.example.foiltracker.core

import kotlin.math.abs
import kotlin.math.atan
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt
import kotlin.math.tan

/**
 * A GPS point consumed by the run-duration algorithm.
 *
 * The timestamp is expressed as Unix epoch milliseconds,
 * exactly like the timestamp that LocationService currently
 * derives from Health Services.
 */
data class TrackPoint(
    val latitude: Double,
    val longitude: Double,
    val timeMs: Long
)

/**
 * Events generated by the run-duration state machine.
 *
 * The Android application uses these to trigger beeps/logging.
 * The CLI does not need to do anything with them.
 */
sealed interface RunDurationEvent {

    data object QualifyingPeriodStarted : RunDurationEvent

    data class QualifyingPeriodEnded(
        val durationSeconds: Long
    ) : RunDurationEvent
}

/**
 * Result of processing one GPS point.
 */
data class ProcessPointResult(
    /**
     * Distance from the previous accepted GPS point.
     */
    val distanceMeters: Float,

    /**
     * Speed calculated from the previous accepted GPS point.
     *
     * This is deliberately in km/h because that is what the
     * existing application exposes.
     */
    val speedKmh: Double,

    /**
     * Whether this point was accepted as a GPX point.
     *
     * The existing application ignores movements smaller than
     * two metres and only writes accepted points to GPX.
     */
    val acceptedForGpx: Boolean,

    /**
     * The value that the application exposes as
     * _runDurationSeconds after this point has been processed.
     */
    val runDurationSeconds: Long,

    /**
     * State-machine events caused by this point.
     */
    val events: List<RunDurationEvent>
)

/**
 * Pure implementation of the run-duration algorithm.
 *
 * This class intentionally has no Android dependencies.
 *
 * LocationService and the command-line program both use this
 * exact class.
 */
class RunDurationCalculator {

    companion object {
        private const val MIN_SPEED_KMH = 10.0
        private const val MAX_SPEED_KMH = 30.0
        private const val MAX_TIME_STEP_SECONDS = 6.0

        /*
         * IMPORTANT:
         *
         * This preserves the behavior of the old implementation.
         *
         * speedKmh is differentiated with respect to seconds, so
         * the actual quantity being compared is km/h per second.
         *
         * The existing constant was named MAX_ACCEL_MPS2, but changing
         * this value or converting units would change behavior.
         */
        // private const val MAX_ACCEL_MPS2 = 5.0

        private const val MIN_TIME_SECONDS = 20.0

        private const val MIN_MOVEMENT_METERS = 2.0f
    }



    val currentRunDurationSeconds: Long
        get() = runDurationSeconds

    private data class SpeedSample(
        val timeMs: Long,
        val speedKmh: Double
    )

    private val speedSamples =
        ArrayDeque<SpeedSample>()

    private var lastPoint: TrackPoint? = null

    private var candidateStartMs: Long? = null

    private var candidateLastMs: Long? = null

    private var above7SinceMs: Long? = null

    private var runDurationSeconds: Long = 0L

    /**
     * Process one GPS point.
     *
     * The returned runDurationSeconds is the exact equivalent of
     * the value that the old LocationService would expose after
     * processing this point.
     */
    fun processPoint(
        point: TrackPoint
    ): ProcessPointResult {

        val previousPoint = lastPoint

        /*
         * First GPS point.
         */
        if (previousPoint == null) {
            lastPoint = point

            return ProcessPointResult(
                distanceMeters = 0.0f,
                speedKmh = 0.0,
                acceptedForGpx = true,
                runDurationSeconds = runDurationSeconds,
                events = emptyList()
            )
        }

        /*
         * Calculate distance between the current point and the
         * previous accepted point.
         *
         * This deliberately matches Android's Location.distanceBetween
         * behavior: WGS84 ellipsoid distance, returned as Float.
         */
        val distanceMeters =
            Wgs84Distance.distanceMeters(
                previousPoint.latitude,
                previousPoint.longitude,
                point.latitude,
                point.longitude
            )

        /*
         * Calculate speed.
         */
        val elapsedSeconds =
            (
                point.timeMs -
                    previousPoint.timeMs
                ) / 1000.0

        val calculatedSpeedKmh =
            if (elapsedSeconds > 0.0) {
                distanceMeters /
                    elapsedSeconds *
                    3.6
            } else {
                0.0
            }

        val events =
            processSpeedSample(
                timeMs = point.timeMs,
                speedKmh = calculatedSpeedKmh
            )

        /*
         * The old LocationService only moved its reference point
         * when the movement was >= 2 metres.
         *
         * Therefore speed calculations also use the previous
         * accepted point rather than literally the previous
         * Health Services point.
         */
        val acceptedForGpx =
            distanceMeters >= MIN_MOVEMENT_METERS

        if (acceptedForGpx) {
            lastPoint = point
        }

        return ProcessPointResult(
            distanceMeters = distanceMeters,
            speedKmh = calculatedSpeedKmh,
            acceptedForGpx = acceptedForGpx,
            runDurationSeconds = runDurationSeconds,
            events = events
        )
    }

    /**
     * Finish a currently active candidate.
     *
     * This is called by LocationService when tracking stops.
     *
     * It is public because the CLI can also use it if it wants to
     * model the end-of-recording behavior.
     */
    fun finish(
        timeMs: Long
    ): List<RunDurationEvent> {
        return finishCandidate(timeMs)
    }

    private fun processSpeedSample(
        timeMs: Long,
        speedKmh: Double
    ): List<RunDurationEvent> {

        /*
         * The existing algorithm rejects speeds outside
         * MIN_SPEED..MAX_SPEED.
         */
        if (speedKmh <= MIN_SPEED_KMH ||
            speedKmh >= MAX_SPEED_KMH
        ) {
            return emptyList()
            // return finishCandidate(timeMs)
        }

        val sample =
            SpeedSample(
                timeMs = timeMs,
                speedKmh = speedKmh
            )

        val previous =
            speedSamples.lastOrNull()

        if (previous != null) {

            val dt =
                (timeMs - previous.timeMs) / 1000.0

            if (dt <= 0.0) {
                return emptyList()
            }

            /*
             * Preserve the existing acceleration calculation exactly.
             */
            val accelerationMps2 =
                (
                    (speedKmh - previous.speedKmh) / 3.6
                ) / dt

                /*
            if (
                kotlin.math.abs(accelerationMps2) >=
                MAX_ACCEL_MPS2
            ) {
                val events =
                    finishCandidate(timeMs)
                speedSamples.clear()
                speedSamples.addLast(sample)
                return events
            }
            */

            /*
             * Preserve the existing chunking behavior.
             */
            if (dt > MAX_TIME_STEP_SECONDS) {
                finishCandidate(timeMs)
                speedSamples.clear()
            }
        }

        speedSamples.addLast(sample)

        /*
         * We now have a valid filtered sequence.
         */
        if (candidateStartMs == null) {
            candidateStartMs = timeMs
        }

        candidateLastMs = timeMs

        val durationSeconds =
            (
                candidateLastMs!! -
                    candidateStartMs!!
                ) / 1000.0

        /*
         * Ruby:
         *
         *   x.last.time - x.first.time > MIN_TIME_S
         */
        if (durationSeconds > MIN_TIME_SECONDS) {

            val events =
                if (above7SinceMs == null) {
                    above7SinceMs = candidateStartMs

                    listOf(
                        RunDurationEvent.QualifyingPeriodStarted
                    )
                } else {
                    emptyList()
                }

            runDurationSeconds =
                durationSeconds.toLong()

            return events
        }

        return emptyList()
    }

    /**
     * Finish the current candidate sequence.
     *
     * Note that runDurationSeconds is intentionally NOT reset.
     * This matches the old LocationService: after a qualifying
     * period ends, the UI continues to see its final duration.
     */
    private fun finishCandidate(
        timeMs: Long
    ): List<RunDurationEvent> {

        val startMs =
            above7SinceMs

        val events =
            if (startMs != null) {

                val endMs =
                    candidateLastMs ?: timeMs

                val duration =
                    (
                        endMs -
                            startMs
                        ) / 1000

                runDurationSeconds =
                    duration

                listOf(
                    RunDurationEvent.QualifyingPeriodEnded(
                        durationSeconds = duration
                    )
                )

            } else {
                emptyList()
            }

        above7SinceMs = null
        candidateStartMs = null
        candidateLastMs = null
        speedSamples.clear()

        return events
    }
}

/**
 * WGS84 distance implementation matching the algorithm used by
 * Android's Location.distanceBetween().
 *
 * Android documents Location.distanceBetween() as a WGS84 ellipsoid
 * calculation. This is the corresponding Vincenty inverse calculation
 * used by AOSP.
 */
private object Wgs84Distance {

    private const val MAX_ITERS = 20

    private const val A = 6378137.0
    private const val B = 6356752.3142

    private const val EPSILON = 1.0e-12

    fun distanceMeters(
        lat1Degrees: Double,
        lon1Degrees: Double,
        lat2Degrees: Double,
        lon2Degrees: Double
    ): Float {

        var lat1 =
            lat1Degrees * Math.PI / 180.0

        var lat2 =
            lat2Degrees * Math.PI / 180.0

        var lon1 =
            lon1Degrees * Math.PI / 180.0

        var lon2 =
            lon2Degrees * Math.PI / 180.0

        val f =
            (A - B) / A

        val aSqMinusBSqOverBSq =
            (A * A - B * B) /
                (B * B)

        val lambdaOriginal =
            lon2 - lon1

        var lambda =
            lambdaOriginal

        val tanU1 =
            (1.0 - f) * tan(lat1)

        val tanU2 =
            (1.0 - f) * tan(lat2)

        val U1 =
            atan(tanU1)

        val U2 =
            atan(tanU2)

        val sinU1 =
            sin(U1)

        val cosU1 =
            cos(U1)

        val sinU2 =
            sin(U2)

        val cosU2 =
            cos(U2)

        var sinLambda = 0.0
        var cosLambda = 0.0
        var sinSigma = 0.0
        var cosSigma = 0.0
        var sigma = 0.0
        var sinAlpha = 0.0
        var cosSqAlpha = 0.0
        var cos2SM = 0.0

        var converged = false

        repeat(MAX_ITERS) {

            sinLambda = sin(lambda)
            cosLambda = cos(lambda)

            val t1 =
                cosU2 * sinLambda

            val t2 =
                cosU1 * sinU2 -
                    sinU1 *
                    cosU2 *
                    cosLambda

            sinSigma =
                sqrt(
                    t1 * t1 +
                        t2 * t2
                )

            if (sinSigma == 0.0) {
                return 0.0f
            }

            cosSigma =
                sinU1 * sinU2 +
                    cosU1 *
                    cosU2 *
                    cosLambda

            sigma =
                atan2(
                    sinSigma,
                    cosSigma
                )

            sinAlpha =
                cosU1 *
                    cosU2 *
                    sinLambda /
                    sinSigma

            cosSqAlpha =
                1.0 -
                    sinAlpha *
                    sinAlpha

            cos2SM =
                if (cosSqAlpha != 0.0) {
                    cosSigma -
                        2.0 *
                        sinU1 *
                        sinU2 /
                        cosSqAlpha
                } else {
                    0.0
                }

            val C =
                (f / 16.0) *
                    cosSqAlpha *
                    (
                        4.0 +
                            f *
                            (
                                4.0 -
                                    3.0 *
                                    cosSqAlpha
                            )
                    )

            val previousLambda =
                lambda

            lambda =
                lambdaOriginal +
                    (1.0 - C) *
                    f *
                    sinAlpha *
                    (
                        sigma +
                            C *
                            sinSigma *
                            (
                                cos2SM +
                                    C *
                                    cosSigma *
                                    (
                                        -1.0 +
                                            2.0 *
                                            cos2SM *
                                            cos2SM
                                    )
                            )
                    )

            val delta =
                (lambda - previousLambda) /
                    lambda

            if (abs(delta) < EPSILON) {
                converged = true
                return@repeat
            }
        }

        /*
         * The Android implementation also proceeds with the latest
         * values if the iteration does not converge.
         */
        @Suppress("UNUSED_VARIABLE")
        val ignored = converged

        val uSq =
            cosSqAlpha *
                aSqMinusBSqOverBSq

        val Acoef =
            1.0 +
                (uSq / 16384.0) *
                (
                    4096.0 +
                        uSq *
                        (
                            -768.0 +
                                uSq *
                                (
                                    320.0 -
                                        175.0 *
                                        uSq
                                )
                        )
                )

        val Bcoef =
            (uSq / 1024.0) *
                (
                    256.0 +
                        uSq *
                        (
                            -128.0 +
                                uSq *
                                (
                                    74.0 -
                                        47.0 *
                                        uSq
                                )
                        )
                )

        val deltaSigma =
            Bcoef *
                sinSigma *
                (
                    cos2SM +
                        (Bcoef / 4.0) *
                        (
                            cosSigma *
                            (
                                -1.0 +
                                    2.0 *
                                    cos2SM *
                                    cos2SM
                            ) -
                                (
                                    Bcoef / 6.0
                                ) *
                                cos2SM *
                                (
                                    -3.0 +
                                        4.0 *
                                        sinSigma *
                                        sinSigma
                                ) *
                                (
                                    -3.0 +
                                        4.0 *
                                        cos2SM *
                                        cos2SM
                                )
                        )
                )

        return (
            B *
                Acoef *
                (sigma - deltaSigma)
            ).toFloat()
    }
}
